import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import './globals.css'
import { defaultTheme } from '@/styles/themes/default'
import { GlobalStyle } from '@/styles/globalStyles'
import AppTheme from '@/shared/app-theme'

const openSans = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={openSans.className}>
        <AppTheme theme={defaultTheme}>
          <GlobalStyle />
          {children}
        </AppTheme>
      </body>
    </html>
  )
}
