import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import '../globals.css'
import { defaultTheme } from '@/styles/themes/default'
import { GlobalStyle } from '@/styles/globalStyles'
import AppTheme from '@/shared/app-theme'

const openSans = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function LocaleLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode
  params: { locale: string }
}>) {
  const messages = await getMessages()

  return (
    <html lang={locale}>
      <body className={openSans.className}>
        <NextIntlClientProvider messages={messages}>
          <AppTheme theme={defaultTheme}>
            <GlobalStyle />
            {children}
          </AppTheme>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
