import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import '@/app/globals.css'
import { defaultTheme } from '@/styles/themes/default'
import { GlobalStyle } from '@/styles/globalStyles'
import AppTheme from '@/shared/app-theme'
import { SessionProvider } from 'next-auth/react'
import { auth } from '@/auth'
const openSans = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function LocaleLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode
  params: { locale: string }
}>) {
  const messages = await getMessages()
  const session = await auth()

  return (
    <html lang={locale}>
      <body className={openSans.className}>
        <SessionProvider session={session}>
          <AppTheme theme={defaultTheme}>
            <NextIntlClientProvider messages={messages}>
              <GlobalStyle />
              {children}
            </NextIntlClientProvider>
          </AppTheme>
        </SessionProvider>
      </body>
    </html>
  )
}
